import json, re

import constants as _C
from utils.Config import Config
from utils.Tools import _warn, _info
from frameworks.Framework import Framework
from frameworks.helper.WATools import WATools

class WAFR(Framework):
    WATools = None
    ResultCache = {}
    isBeta = False
    def __init__(self, data):
        super().__init__(data)
        self.isBeta = Config.get('beta', False)

        self.WATools = None
        waTools = WATools('reliability')
        cliParams = Config.get('_SS_PARAMS')

        tmpParams = {}
        self.ResultCache = {}
        if 'others' in cliParams and not cliParams['others'] == None:
            params = cliParams['others']
            cfg = json.loads(params)

            if 'WA' in cfg:
                tmpParams = cfg['WA']

        if waTools.preCheck(tmpParams): 
            self.WATools = waTools
            self.WATools.init(tmpParams)
            self.WATools.createReportIfNotExists()
            self.WATools.listAnswers()

    def _hookPostItemActivity(self, title, section, checks, comp):
        if self.WATools == None or self.WATools.HASPERMISSION == False or not hasattr(self.WATools, 'answerSets'):
            return title, section, checks, comp
        
        titleNum = self.extractNumber(title)
        sectNum = self.extractNumber(section)

        paired = "{}::{}".format(titleNum, sectNum)

        newChecks = "<h4>{}</h4>{}".format(self.getDescription(titleNum, paired), checks) 

        titleKey = self.WATools.answerSets.get(titleNum, [None])[0]
        if not titleKey in self.ResultCache:
            self.ResultCache[titleKey] = {
                "0": [],
                "1": [],
                "-1": []
            }

        if not titleKey == None:
            if comp == 1:
                self.ResultCache[titleKey]["1"].append(self.WATools.answerSets.get(paired, [None])[0])
            elif comp == -1:
                self.ResultCache[titleKey]["-1"].append(self.WATools.answerSets.get(paired, [None, None])[1])
            else:
                self.ResultCache[titleKey]["0"].append(self.WATools.answerSets.get(paired, [None])[0])

        return title, section, newChecks, comp
        
    def _hookPostItemsLoop(self):
        if self.WATools == None or self.WATools.HASPERMISSION == False:
            return

        for title, opts in self.ResultCache.items():
            if len(opts["1"]) == 0 and len(opts["-1"]) == 0:
                continue 

            # Filter out None values from the selected choices
            ansStr = [choice for choice in opts["1"] if choice is not None]
            unselectedNotes = "***Generated by SS\n\nHere are the items failed SS checks (if any):\n- {}".format("\n- ".join([item for item in opts["-1"] if item is not None]))

            self.WATools.updateAnswers(title, ansStr, unselectedNotes)

        pass

    def extractNumber(self, s):
        match = re.search(r'\d+', s)
        return match.group() if match else None
    
    def getDescription(self, titleNum, paired):
        if self.WATools == None or self.WATools.HASPERMISSION == False or not hasattr(self.WATools, 'answerSets'):
            return f"REL{titleNum} - Best Practice {paired.split('::')[1] if '::' in paired else paired}"
        
        titleData = self.WATools.answerSets.get(titleNum, [None, None])
        pairedData = self.WATools.answerSets.get(paired, [None, None])
        
        titleStr = titleData[1] if len(titleData) > 1 and titleData[1] else f"REL{titleNum}"
        sectStr = pairedData[1] if len(pairedData) > 1 and pairedData[1] else f"BP{paired.split('::')[1] if '::' in paired else paired}"
        
        return f"{titleStr} - {sectStr}"

    def _hookPostBuildContentDetail(self):
        self.WATools.createMilestoneIfNotExists()